### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by gaiyayishi** [NSACloud/NieR-Audio-Tools#1]
``````
core_pl_AS_black_illusion_lv3   {r}
core_pl_AS_black_illusion_lv3 {r}
core_pl_AS_black_illusion_lv3 {r}
core_pl_AS_black_illusion_lv3 {r}
core_pl_AS_black_spear_charge
core_pl_AS_black_spear_hit {r}
core_pl_AS_black_spear_hit {r}
core_pl_AS_black_spear_hit {r}
``````

these many files in SoundNames_automata.csv  are missing
though something like BGM\vo  files remain

What have I missed  in   \data\sound ?

**Comment by NSACloud** [comment]
Those sounds are in various bnks inside dat files packed into the cpks. BGM and character dialogue is in the .wsp's, I'll have a tool for extracting and repacking those probably next week. The current wsp tool doesn't handle names.

**Comment by gaiyayishi** [comment]
> Those sounds are in various bnks inside dat files packed into the cpks. BGM and character dialogue is in the .wsp's, I'll have a tool for extracting and repacking those probably next week. The current wsp tool doesn't handle names.

!
could you teach me how to unpack the cpks and dat files

**Comment by NSACloud** [comment]
CripakGUI for cpk https://github.com/wmltogether/CriPakTools/releases/download/v20161116/CriPakGUI.zip
PlatinumDat for dat
https://drive.google.com/file/d/0B87z--RxNuh4MUNUMHFxOF9mV0U/view

**Comment by gaiyayishi** [comment]
> CripakGUI for cpk https://github.com/wmltogether/CriPakTools/releases/download/v20161116/CriPakGUI.zip
> PlatinumDat for dat
> https://drive.google.com/file/d/0B87z--RxNuh4MUNUMHFxOF9mV0U/view

Thank you very much!
